# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('ability', models.DecimalField(decimal_places=5, max_digits=6)),
            ],
        ),
    ]
