# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_learner_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='responses',
            field=models.TextField(null=True),
        ),
    ]
